[package]
name = "magnetic"
description = "Low-latency lock-free queues"
version = "1.0.1"
authors = ["John Shaw <jshaw@shawnation.com>"]
license = "MIT"
repository = "https://github.com/johnshaw/magnetic"
keywords = ["lock-free", "queue"]
documentation = "http://johnshaw.github.io/doc/magnetic/magnetic"
